echo go run . "example.txt"
go run . "examples/example.txt"
echo "----------------------------------------------------------------"
echo go run . "example00.txt"
go run . "examples/example00.txt"
echo "----------------------------------------------------------------"
echo go run . "example01.txt"
go run . "examples/example01.txt"
echo "----------------------------------------------------------------"
echo go run . "example02.txt"
go run . "examples/example02.txt"
echo "----------------------------------------------------------------"
echo go run . "example03.txt"
go run . "examples/example03.txt"
echo "----------------------------------------------------------------"
echo go run . "example04.txt"
go run . "examples/example04.txt"
echo "----------------------------------------------------------------"
echo go run . "example05.txt"
go run . "examples/example05.txt"
echo "----------------------------------------------------------------"
echo go run . "example06.txt"
go run . "examples/example06.txt"

